const ChapterPages = [
    {
        id: 1,
        title: 'Prologue',
        page: 2,
        pageTab: 2,
        pageMobile: 2,
        subpage: false,
        pageIndex: 2,
        pageIndexTab: 2,
        pageIndexMobile: 2,
    },
    {
        id: 2,
        title: 'Chapter 1: The Inception',
        page: 5,
        pageTab: 2,
        pageMobile: 2,
        subpage: false,
        pageIndex: 4,
        pageIndexTab: 2,
        pageIndexMobile: 2,
    },
    {
        id: 3,
        title: 'The Tale of AbracaDoobie',
        page: 11,
        pageTab: 2,
        pageMobile: 2,
        subpage: true,
        pageIndex: 7,
        pageIndexTab: 2,
        pageIndexMobile: 2,
    },
    {
        id: 4,
        title: 'The Tale of Aster',
        page: 13,
        pageTab: 2,
        pageMobile: 2,
        subpage: true,
        pageIndex: 8,
        pageIndexTab: 2,
        pageIndexMobile: 2,
    },
    {
        id: 5,
        title: 'The Tale of Bacon Prince',
        page: 15,
        pageTab: 2,
        pageMobile: 2,
        subpage: true,
        pageIndex: 9,
        pageIndexTab: 2,
        pageIndexMobile: 2,
    },
    {
        id: 6,
        title: 'The Tale of Bandwip',
        page: 17,
        pageTab: 2,
        pageMobile: 2,
        subpage: true,
        pageIndex: 10,
        pageIndexTab: 2,
        pageIndexMobile: 2,
    },
    {
        id: 7,
        title: 'The Tale of Bee Lee',
        page: 19,
        pageTab: 2,
        pageMobile: 2,
        subpage: true,
        pageIndex: 11,
        pageIndexTab: 2,
        pageIndexMobile: 2,
    },
    {
        id: 8,
        title: 'The Tale of Berry',
        page: 21,
        pageTab: 2,
        pageMobile: 2,
        subpage: true,
        pageIndex: 12,
        pageIndexTab: 2,
        pageIndexMobile: 2,
    },
    {
        id: 9,
        title: 'The Tale of Bug',
        page: 23,
        pageTab: 2,
        pageMobile: 2,
        subpage: true,
        pageIndex: 13,
        pageIndexTab: 2,
        pageIndexMobile: 2,
    },
    {
        id: 10,
        title: 'The Tale of Cairo',
        page: 25,
        pageTab: 2,
        pageMobile: 2,
        subpage: true,
        pageIndex: 14,
        pageIndexTab: 2,
        pageIndexMobile: 2,
    },
    {
        id: 11,
        title: 'The Tale of Gamer Boi',
        page: 27,
        pageTab: 2,
        pageMobile: 2,
        subpage: true,
        pageIndex: 15,
        pageIndexTab: 2,
        pageIndexMobile: 2,
    },
    {
        id: 12,
        title: 'The Tale of Pulsar',
        page: 29,
        pageTab: 2,
        pageMobile: 2,
        subpage: true,
        pageIndex: 16,
        pageIndexTab: 2,
        pageIndexMobile: 2,
    },
    {
        id: 13,
        title: 'Chapter 2: The Blade at Fellowcro',
        page: 32,
        pageTab: 2,
        pageMobile: 2,
        subpage: false,
        pageIndex: 17,
        pageIndexTab: 2,
        pageIndexMobile: 2,
    },
    {
        id: 14,
        title: 'The Tale of Candy Cane',
        page: 39,
        pageTab: 2,
        pageMobile: 2,
        subpage: true,
        pageIndex: 21,
        pageIndexTab: 2,
        pageIndexMobile: 2,
    },
    {
        id: 15,
        title: 'The Tale of Candy Witch',
        page: 41,
        pageTab: 2,
        pageMobile: 2,
        subpage: true,
        pageIndex: 22,
        pageIndexTab: 2,
        pageIndexMobile: 2,
    },
    {
        id: 16,
        title: 'The Tale of CarabaoHead',
        page: 43,
        pageTab: 2,
        pageMobile: 2,
        subpage: true,
        pageIndex: 23,
        pageIndexTab: 2,
        pageIndexMobile: 2,
    },
    {
        id: 17,
        title: 'The Tale of Carbon',
        page: 45,
        pageTab: 2,
        pageMobile: 2,
        subpage: true,
        pageIndex: 24,
        pageIndexTab: 2,
        pageIndexMobile: 2,
    },
    {
        id: 18,
        title: 'The Tale of Caster',
        page: 47,
        pageTab: 2,
        pageMobile: 2,
        subpage: true,
        pageIndex: 25,
        pageIndexTab: 2,
        pageIndexMobile: 2,
    },
    {
        id: 19,
        title: 'The Tale of Catch A Wave',
        page: 49,
        pageTab: 2,
        pageMobile: 2,
        subpage: true,
        pageIndex: 26,
        pageIndexTab: 2,
        pageIndexMobile: 2,
    },
    {
        id: 20,
        title: 'The Tale of Cave Wizard',
        page: 51,
        pageTab: 2,
        pageMobile: 2,
        subpage: true,
        pageIndex: 27,
        pageIndexTab: 2,
        pageIndexMobile: 2,
    },
    {
        id: 21,
        title: 'The Tale of Climber',
        page: 53,
        pageTab: 2,
        pageMobile: 2,
        subpage: true,
        pageIndex: 28,
        pageIndexTab: 2,
        pageIndexMobile: 2,
    },
    {
        id: 22,
        title: 'The Tale of Rench',
        page: 55,
        pageTab: 2,
        pageMobile: 2,
        subpage: true,
        pageIndex: 29,
        pageIndexTab: 2,
        pageIndexMobile: 2,
    },
    {
        id: 23,
        title: 'The Tale of Shucks',
        page: 57,
        pageTab: 2,
        pageMobile: 2,
        subpage: true,
        pageIndex: 30,
        pageIndexTab: 2,
        pageIndexMobile: 2,
    },
    {
        id: 24,
        title: 'Chapter 3: Coming Soon...',
        page: '',
        pageTab: '',
        pageMobile: '',
        subpage: false,
        pageIndex: 1,
        pageIndexTab: 2,
        pageIndexMobile: 2,
    },
]

export default ChapterPages